"""dna-rights CLI — Natural rights assertion toolkit."""

import json
import os
import re
import sys
from pathlib import Path

import click
import yaml
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

console = Console()

DATA_DIR = Path(__file__).resolve().parent.parent.parent / "data"
TERMS_FILE = DATA_DIR / "terms.yaml"

# ---------------------------------------------------------------------------
# Term database (YAML-backed, LLM-expandable)
# ---------------------------------------------------------------------------

def load_terms() -> dict:
    """Load term mappings from YAML data file."""
    if TERMS_FILE.exists():
        return yaml.safe_load(TERMS_FILE.read_text()) or {}
    return {}


def save_terms(db: dict) -> None:
    """Write terms back to YAML, preserving the header comment."""
    header = (
        "# terms.yaml — Natural rights term database\n"
        "# Each term has: biological equivalent, framework (legal/natural), "
        "jurisdiction, implication.\n"
        "# New terms are generated by LLM and appended here.\n"
        "# Source: dna-rights conceptual framework "
        "(natural rights vs legal constructs)\n\n"
    )
    TERMS_FILE.parent.mkdir(parents=True, exist_ok=True)
    TERMS_FILE.write_text(
        header + yaml.dump(db, default_flow_style=False, sort_keys=False, allow_unicode=True)
    )


def generate_term(term: str) -> dict | None:
    """Use Claude to generate a natural rights term analysis."""
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return None

    try:
        import anthropic
        client = anthropic.Anthropic()
    except Exception:
        return None

    system = (
        "You are a natural rights language analyst. You analyze legal and "
        "natural rights terms through the lens of biological parentage and "
        "natural law.\n\n"
        "For each term, provide:\n"
        "- biological: the natural/biological equivalent of this term "
        "(e.g., 'children' → 'offspring', 'custody' → 'natural bond')\n"
        "- framework: either 'legal' (state-created construct) or 'natural' "
        "(exists by biology/nature)\n"
        "- jurisdiction: what legal jurisdiction this term operates in "
        "(e.g., 'Statutory — 750 ILCS...' or 'Natural law — ...')\n"
        "- implication: what accepting or asserting this term means for "
        "jurisdiction and standing (1-2 sentences)\n\n"
        "Key principle: legal terms accept the court's jurisdiction. "
        "Natural terms assert biological facts the court cannot adjudicate.\n\n"
        "Respond ONLY with valid YAML (no markdown fences, no commentary) in this exact format:\n"
        "biological: ...\n"
        "framework: legal|natural\n"
        "jurisdiction: ...\n"
        "implication: ..."
    )

    console.print(f"[dim]Generating term analysis for '[/dim][bold]{term}[/bold][dim]'...[/dim]")

    try:
        resp = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=300,
            system=system,
            messages=[{"role": "user", "content": f"Analyze the term: {term}"}],
        )
        text = resp.content[0].text.strip()
        text = re.sub(r'^```\w*\n?', '', text)
        text = re.sub(r'\n?```$', '', text)
        entry = yaml.safe_load(text)
        if isinstance(entry, dict) and all(
            k in entry for k in ("biological", "framework", "jurisdiction", "implication")
        ):
            return entry
    except Exception as e:
        console.print(f"[red]Generation failed: {e}[/red]")

    return None


# ---------------------------------------------------------------------------
# Reframe patterns
# ---------------------------------------------------------------------------

REFRAME_PATTERNS = {
    "custody of": "natural bond with",
    "custody": "natural bond",
    "the minor child": "the offspring",
    "the minor children": "the offspring",
    "minor child": "offspring",
    "minor children": "offspring",
    "my children": "my offspring",
    "the children": "the offspring",
    "his children": "his offspring",
    "her children": "her offspring",
    "their children": "their offspring",
    "the child": "the offspring",
    "children": "offspring",
    "child": "offspring",
    "visitation": "access to offspring",
    "parenting time": "access to offspring",
    "custodial parent": "parent with offspring in their care",
    "non-custodial parent": "parent denied access to offspring",
    "noncustodial parent": "parent denied access to offspring",
    "best interest of the child": "natural right of the parent-offspring bond",
    "best interests of the child": "natural rights of the parent-offspring bond",
    "guardian ad litem": "court-appointed representative",
    "termination of parental rights": "attempted severance of a biological bond",
    "ward of the court": "offspring under court control",
    "ward": "offspring",
}

# ---------------------------------------------------------------------------
# Authority citations
# ---------------------------------------------------------------------------

AUTHORITIES = {
    "natural": [
        "John Locke, Second Treatise of Government (1689) — natural rights precede government",
        "William Blackstone, Commentaries (1765) — parent-child relation is the most universal in nature",
        "Declaration of Independence (1776) — unalienable rights endowed by Creator",
    ],
    "constitutional": [
        "Meyer v. Nebraska, 262 U.S. 390 (1923) — liberty includes right to raise children",
        "Pierce v. Society of Sisters, 268 U.S. 510 (1925) — child is not mere creature of the state",
        "Stanley v. Illinois, 405 U.S. 645 (1972) — unwed father has protected interest",
        "Troxel v. Granville, 530 U.S. 57 (2000) — oldest of fundamental liberty interests",
        "Santosky v. Kramer, 455 U.S. 745 (1982) — heightened standard for termination",
    ],
    "international": [
        "UN CRC Article 7 — right to know parents",
        "UN CRC Article 8 — preservation of identity",
        "UN CRC Article 9 — non-separation from parents",
        "UN CRC Article 18 — both parents responsible",
        "ECHR Article 8 — right to respect for family life",
        "UDHR Article 16(3) — family is the natural and fundamental group unit",
    ],
}


def _output(data: dict, fmt: str, title: str = ""):
    """Render output in the requested format."""
    if fmt == "json":
        console.print_json(json.dumps(data, indent=2))
    else:
        if "panel" in data:
            console.print(Panel(data["panel"], title=title, border_style="bold cyan"))
        if "table" in data:
            console.print(data["table"])
        if "sections" in data:
            for section_title, content in data["sections"]:
                console.print()
                console.print(Panel(content, title=section_title, border_style="cyan"))


# ---------------------------------------------------------------------------
# CLI group
# ---------------------------------------------------------------------------

@click.group()
def main():
    """dna-rights: Natural rights assertion toolkit.

    Assert biological parentage as a jurisdictional fact independent of any court.
    """
    pass


# ---------------------------------------------------------------------------
# rights compare
# ---------------------------------------------------------------------------

@main.command()
@click.argument("term1")
@click.argument("term2")
@click.option("--format", "fmt", type=click.Choice(["text", "json"]), default="text")
@click.option("--no-generate", is_flag=True, help="Don't generate missing terms via LLM.")
def compare(term1, term2, fmt, no_generate):
    """Side-by-side jurisdictional analysis of two terms.

    Unknown terms are generated by LLM and saved to the term database.
    """
    db = load_terms()
    t1 = term1.lower()
    t2 = term2.lower()
    generated = []

    for t in [t1, t2]:
        if t not in db:
            if no_generate:
                available = ", ".join(sorted(db.keys()))
                console.print(f"[red]Term '{t}' not found.[/red]")
                console.print(f"[dim]Available: {available}[/dim]")
                sys.exit(1)
            entry = generate_term(t)
            if entry is None:
                console.print(f"[red]Term '{t}' not found and generation failed.[/red]")
                console.print("[dim]Check ANTHROPIC_API_KEY is set.[/dim]")
                sys.exit(1)
            db[t] = entry
            generated.append(t)

    if generated:
        save_terms(db)

    info1 = db[t1]
    info2 = db[t2]

    if fmt == "json":
        _output(
            {
                "type": "term_comparison",
                "term1": {"term": t1, **info1},
                "term2": {"term": t2, **info2},
                "generated": generated,
            },
            fmt,
        )
        return

    table = Table(
        title=f"Jurisdictional Comparison: '{t1}' vs '{t2}'",
        show_header=True,
        header_style="bold cyan",
        border_style="cyan",
    )
    table.add_column("Dimension", style="bold")
    table.add_column(t1, style="red" if info1["framework"] == "legal" else "green")
    table.add_column(t2, style="red" if info2["framework"] == "legal" else "green")

    table.add_row("Framework", info1["framework"], info2["framework"])
    table.add_row("Biological Equivalent", info1["biological"], info2["biological"])
    table.add_row("Jurisdiction", info1["jurisdiction"], info2["jurisdiction"])
    table.add_row("Implication", info1["implication"], info2["implication"])

    console.print()
    console.print(table)

    if info1["framework"] != info2["framework"]:
        legal_term = t1 if info1["framework"] == "legal" else t2
        natural_term = t2 if info1["framework"] == "legal" else t1
        console.print()
        console.print(
            Panel(
                f"[bold]'{legal_term}'[/bold] operates in the [red]legal[/red] framework. "
                f"[bold]'{natural_term}'[/bold] operates in the [green]natural[/green] framework.\n\n"
                f"Using '{legal_term}' accepts the court's jurisdiction. "
                f"Using '{natural_term}' asserts a biological fact the court cannot adjudicate.",
                title="[bold]Jurisdictional Shift[/bold]",
                border_style="yellow",
            )
        )

    if generated:
        console.print(
            f"[dim]Generated: {', '.join(generated)}. "
            f"Saved to {TERMS_FILE.name} ({len(db)} terms in database).[/dim]"
        )
    console.print()


# ---------------------------------------------------------------------------
# rights assert
# ---------------------------------------------------------------------------

@main.command("assert")
@click.option("--relationship", default="parent-offspring", help="Relationship to assert.")
@click.option("--evidence", default="dna", help="Basis for assertion.")
@click.option("--format", "fmt", type=click.Choice(["text", "json"]), default="text")
def assert_(relationship, evidence, fmt):
    """Generate a formal assertion of natural rights based on biological parentage."""
    assertion_text = (
        f"ASSERTION OF NATURAL RIGHTS\n\n"
        f"Relationship: {relationship}\n"
        f"Basis: {evidence.upper()}\n\n"
        f"The {relationship} bond is a natural right that exists by biology, "
        f"not by state grant. This bond was established at conception, is encoded "
        f"in DNA, and is beyond the jurisdiction of any court to create, modify, "
        f"or destroy.\n\n"
        f"The undersigned asserts the following:\n\n"
        f"1. The biological {relationship} bond exists as a fact of nature, "
        f"independent of any legal proceeding.\n\n"
        f"2. No court order created this bond. No court order can sever it.\n\n"
        f"3. DNA evidence does not 'prove' this bond to a court — it reveals "
        f"what already exists independent of any court.\n\n"
        f"4. Any legal proceeding that purports to modify the biological "
        f"{relationship} bond operates ultra vires — beyond the court's "
        f"jurisdiction.\n\n"
        f"5. The undersigned demands that any court asserting jurisdiction over "
        f"this biological bond identify the specific authority under which it "
        f"claims that jurisdiction."
    )

    authorities_text = "\n".join(
        f"  - {a}" for level in ["natural", "constitutional", "international"]
        for a in AUTHORITIES[level]
    )

    if fmt == "json":
        _output(
            {
                "type": "natural_rights_assertion",
                "relationship": relationship,
                "evidence": evidence,
                "assertion": assertion_text,
                "authorities": {
                    level: AUTHORITIES[level]
                    for level in ["natural", "constitutional", "international"]
                },
            },
            fmt,
        )
    else:
        panel_text = assertion_text + f"\n\n[bold]Authorities:[/bold]\n{authorities_text}"
        _output(
            {"panel": panel_text},
            fmt,
            title="[bold white]ASSERTION OF NATURAL RIGHTS[/bold white]",
        )


# ---------------------------------------------------------------------------
# rights claim
# ---------------------------------------------------------------------------

@main.command()
@click.option("--type", "claim_type", default="offspring", help="Type of claim.")
@click.option("--context", default="court", help="Context for the claim.")
@click.option("--format", "fmt", type=click.Choice(["text", "json"]), default="text")
def claim(claim_type, context, fmt):
    """Draft a DNA-based standing claim for court submission."""
    sections = [
        (
            "1. ESTABLISHMENT OF BIOLOGICAL FACT",
            "Respondent is the biological parent of the offspring identified herein, "
            "as established by DNA. This biological relationship was created at "
            "conception and exists independent of any legal proceeding, court order, "
            "or statutory framework.",
        ),
        (
            "2. ASSERTION OF NATURAL RIGHT",
            "The parent-offspring bond is a natural right recognized by the Supreme "
            "Court as 'the oldest of the fundamental liberty interests.' "
            "(Troxel v. Granville, 530 U.S. 57, 65 (2000)). This right is not "
            "created by statute and cannot be extinguished by court order. It exists "
            "by nature, established by DNA, and predates any legal system.",
        ),
        (
            "3. CHALLENGE TO JURISDICTION",
            "This Court has jurisdiction over legal relationships created by statute. "
            "The biological bond between a parent and their offspring was not created "
            "by statute. Respondent respectfully demands that this Court identify the "
            "specific authority under which it claims jurisdiction over a biological fact.",
        ),
        (
            "4. DEMAND FOR PERFORMANCE",
            "If this Court asserts jurisdiction over the biological parent-offspring "
            "bond, Respondent demands that the Court specifically identify:\n\n"
            "  (a) The source of that authority;\n"
            "  (b) The legal basis for overriding a natural right;\n"
            "  (c) The standard by which a biological fact becomes subject to "
            "judicial modification;\n"
            "  (d) The compelling state interest that justifies interference with "
            "the most fundamental of natural bonds.",
        ),
    ]

    if fmt == "json":
        _output(
            {
                "type": "dna_standing_claim",
                "claim_type": claim_type,
                "context": context,
                "sections": [
                    {"title": t, "content": c} for t, c in sections
                ],
                "authorities": AUTHORITIES,
            },
            fmt,
        )
    else:
        console.print()
        console.print(
            Panel(
                f"[bold]Claim Type:[/bold] {claim_type}\n"
                f"[bold]Context:[/bold] {context}\n"
                f"[bold]Basis:[/bold] DNA — biological parentage as jurisdictional fact",
                title="[bold white]DNA-BASED STANDING CLAIM[/bold white]",
                border_style="bold cyan",
            )
        )
        _output({"sections": sections}, fmt)


# ---------------------------------------------------------------------------
# rights reframe
# ---------------------------------------------------------------------------

@main.command()
@click.argument("text")
@click.option("--format", "fmt", type=click.Choice(["text", "json"]), default="text")
def reframe(text, fmt):
    """Rewrite statutory/legal language in natural rights terms."""
    original = text
    reframed = text
    changes = []

    sorted_patterns = sorted(REFRAME_PATTERNS.keys(), key=len, reverse=True)

    for legal_term in sorted_patterns:
        natural_term = REFRAME_PATTERNS[legal_term]
        lower_reframed = reframed.lower()
        idx = lower_reframed.find(legal_term.lower())
        while idx != -1:
            found_text = reframed[idx : idx + len(legal_term)]
            reframed = reframed[:idx] + natural_term + reframed[idx + len(legal_term):]
            changes.append({"from": found_text, "to": natural_term})
            lower_reframed = reframed.lower()
            idx = lower_reframed.find(legal_term.lower(), idx + len(natural_term))

    if fmt == "json":
        _output(
            {"type": "reframed_text", "original": original, "reframed": reframed, "changes": changes},
            fmt,
        )
    else:
        console.print()
        console.print(Panel(
            f"[red strikethrough]{original}[/red strikethrough]",
            title="[bold]Original (Legal Framing)[/bold]", border_style="red",
        ))
        console.print(Panel(
            f"[bold green]{reframed}[/bold green]",
            title="[bold]Reframed (Natural Rights)[/bold]", border_style="green",
        ))

        if changes:
            table = Table(title="Term Substitutions", show_header=True, header_style="bold", border_style="cyan")
            table.add_column("Legal Term", style="red")
            table.add_column("Natural Rights Term", style="green")
            for change in changes:
                table.add_row(change["from"], change["to"])
            console.print()
            console.print(table)
        else:
            console.print()
            console.print("[yellow]No legal terms found to reframe.[/yellow]")


if __name__ == "__main__":
    main()
